# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1006, 681)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 981, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TVLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TVLabel.setObjectName("TVLabel")
        self.verticalLayout_2.addWidget(self.TVLabel)
        self.RadioCats = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RadioCats.setObjectName("RadioCats")
        self.verticalLayout_2.addWidget(self.RadioCats)
        self.CPULabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.CPULabel.setObjectName("CPULabel")
        self.verticalLayout_2.addWidget(self.CPULabel)
        self.radioRandom = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioRandom.setObjectName("radioRandom")
        self.verticalLayout_2.addWidget(self.radioRandom)
        self.radioSure = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioSure.setObjectName("radioSure")
        self.verticalLayout_2.addWidget(self.radioSure)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ClocLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ClocLabel.setObjectName("ClocLabel")
        self.verticalLayout_3.addWidget(self.ClocLabel)
        self.radio30 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio30.setObjectName("radio30")
        self.verticalLayout_3.addWidget(self.radio30)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioVariable = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioVariable.setObjectName("radioVariable")
        self.horizontalLayout_2.addWidget(self.radioVariable)
        self.TimeSelector = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.TimeSelector.setObjectName("TimeSelector")
        self.horizontalLayout_2.addWidget(self.TimeSelector)
        self.SecLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.SecLabel.setObjectName("SecLabel")
        self.horizontalLayout_2.addWidget(self.SecLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.radioRelaxed = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioRelaxed.setObjectName("radioRelaxed")
        self.verticalLayout_3.addWidget(self.radioRelaxed)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushStart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushStart.setObjectName("pushStart")
        self.verticalLayout.addWidget(self.pushStart)
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)
        self.actionNew_Game = QtWidgets.QAction(MainMenu)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionExit = QtWidgets.QAction(MainMenu)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew_Game)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "MainWindow"))
        self.TVLabel.setText(_translate("MainMenu", "Vs Tv"))
        self.RadioCats.setText(_translate("MainMenu", "Cats"))
        self.CPULabel.setText(_translate("MainMenu", "Vs CPU"))
        self.radioRandom.setText(_translate("MainMenu", "Random"))
        self.radioSure.setText(_translate("MainMenu", "Sure Answer"))
        self.ClocLabel.setText(_translate("MainMenu", "Clock"))
        self.radio30.setText(_translate("MainMenu", "30 Sec"))
        self.radioVariable.setText(_translate("MainMenu", "Variable"))
        self.SecLabel.setText(_translate("MainMenu", "Secs"))
        self.radioRelaxed.setText(_translate("MainMenu", "Relaxed"))
        self.pushStart.setText(_translate("MainMenu", "Start"))
        self.menuFile.setTitle(_translate("MainMenu", "File"))
        self.actionNew_Game.setText(_translate("MainMenu", "New Game"))
        self.actionExit.setText(_translate("MainMenu", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())

